### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by thomasms** [mdavidsaver/pvxs#14]
Not really an issue, more of an enquiry. 

I've been looking at using pvData and pvAccess but don't want to start adopting something that is expected to be deprecated.
Am I correct in thinking PVXS is expected to supersede pvData and pvAccess in the near future? Can PVXS already be used in production?

Are you able to indicate when the API will become stable with an associated release?

**Comment by mdavidsaver** [comment]
Quoting myself from [other](https://epics.anl.gov/tech-talk/2020/msg00808.php) [forums](https://epics.anl.gov/tech-talk/2020/msg02255.php).

> This _(0.1.0)_ is the first of what I'm calling a "pre-production" release series.  This is the point from which I will start keeping release notes to give users visibility into any significant functional or API changes.

So far I haven't made any backwards incompatible API changes, and I don't have any planned.  However, I'm not going to rule out the possibility if some comes up in the future.

As per my [release policy](https://mdavidsaver.github.io/pvxs/details.html#release-policy) any incompatible change would be reflected in a release number, and in the [release notes](https://mdavidsaver.github.io/pvxs/releasenotes.html), and likely in pull request here on github.  Which is to say, that I'll try to give users some advanced notice, and a chance weigh in.

**Comment by thomasms** [comment]
OK great. Thanks. I will close this issue.
