### ISSUE TITLE
Debian needs libevent-dev instead of libevent2-dev

### ISSUE THREAD

**Issue by jeonghanlee** [mdavidsaver/pvxs#2]
I couldn't find libevent2-dev [1] in Debian 10. Could you check it again? 

[1] https://github.com/mdavidsaver/pvxs/blob/master/documentation/building.rst

**Comment by mdavidsaver** [comment]
Right, it's called [libevent-dev](https://packages.debian.org/search?keywords=libevent-dev) now (and for most of the past decade...).

**Comment by jeonghanlee** [comment]
Should I pull request for the document? If this help you, I can do this.

**Comment by mdavidsaver** [comment]
I already have the correction committed locally.  I'm not going to push it yet as my CI build queues are full of unrelated jobs.

**Comment by jeonghanlee** [comment]
[skip-ci] ? ;) thank you.

**Comment by mdavidsaver** [comment]
There is also the MD queue, which is harder to skip.  Fixed with 51663e1cfdc045a080aaebb44c611e3aed5d15d9 and published.
