### ISSUE TITLE
ci-scripts submodule is using non-existing commit

### ISSUE THREAD

**Issue by ericonr** [mdavidsaver/pvxs#54]
**Describe the bug**

The commit in use by `ci-scripts`, https://github.com/mdavidsaver/ci-scripts/tree/a8bffdcfb73e7710662185d77e7cc0662a1deede , has a warning about not belonging to the repository, "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.", because it only exists in the `epics-base` repo: https://github.com/epics-base/ci-scripts/commit/a8bffdcfb73e7710662185d77e7cc0662a1deede

Updating https://github.com/mdavidsaver/ci-scripts would be enough, but would it make sense to move to using the `epics-base` repo directly instead?

I noticed this because my local clone can't fetch the submodule's commit

**Comment by mdavidsaver** [comment]
> "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

Resolved.  I am surprised that github actions have been running these past two months.


> but would it make sense to move to using the `epics-base` repo directly instead?

Probably.  At this stage, I am not working with ci-scripts changes as much.

**Comment by ericonr** [comment]
> Resolved. I am surprised that github actions have been running these past two months.

I assume using the checkout action does some magic, though from the log I can't really tell anything:

```
Fetching submodules
  /usr/bin/git submodule sync
  /usr/bin/git -c protocol.version=2 submodule update --init --force --depth=1
  Submodule '.ci' (https://github.com/mdavidsaver/ci-scripts) registered for path '.ci'
  Submodule 'bundle/libevent' (https://github.com/libevent/libevent) registered for path 'bundle/libevent'
  Cloning into '/home/runner/work/pvxs/pvxs/.ci'...
  Cloning into '/home/runner/work/pvxs/pvxs/bundle/libevent'...
  From https://github.com/mdavidsaver/ci-scripts
   * branch            a8bffdcfb73e7710662185d77e7cc0662a1deede -> FETCH_HEAD
  Submodule path '.ci': checked out 'a8bffdcfb73e7710662185d77e7cc0662a1deede'
  Submodule path 'bundle/libevent': checked out 'c9ec6aafb6a025f03636ae2ae7c18a2d4b8a7ed8'
  /usr/bin/git submodule foreach git config --local gc.auto 0
  Entering '.ci'
  Entering 'bundle/libevent'
```

> Probably. At this stage, I am not working with ci-scripts changes as much.

Would it be of any help to open a PR? Otherwise I can just close this issue.

**Comment by mdavidsaver** [comment]
> > Probably. At this stage, I am not working with ci-scripts changes as much.

09a3f018a2dd0c8271c02245ef3407592c6f8791 does this.

> Would it be of any help to open a PR? Otherwise I can just close this issue.

Having only to click "merge" may sometimes help me overcome my tendency to procrastinate.

**Comment by ericonr** [comment]
> Having only to click "merge" may sometimes help me overcome my tendency to procrastinate.

Noted for future issues ^-^

Thanks!
